export const CHANGE_USERNAME = 'boilerplate/Home/CHANGE_USERNAME';
export const SEND_REQUEST_BUNDLE = 'SEND_REQUEST_BUNDLE';
export  const RECEIVE_REQUEST_BUNDLE_RESULT = 'RECEIVE_REQUEST_BUNDLE_RESULT';
